name: Create a comment action
on:
  issues:
    types: [opened]
permissions: 
  issues: write
jobs:
  comment-with-action:
    runs-on: ubuntu-latest
    steps:
     - name: 'dump github context'
       run: echo '${{toJson(github.event)}}' | jq
       shell: bash
     - name: Create comment
       uses: peter-evans/create-or-update-comment@v5
       with:
          issue-number: ${{github.event.issue.number}}
          body: |
            This is a multi-line test comment
            - With GitHub **Markdown** :sparkles:
            - Created by [create-or-update-comment][1]
  
            [1]: https://github.com/peter-evans/create-or-update-comment
          reactions: '+1'

  comments-with-api:
    runs-on: ubuntu-latest
    steps:
      - name: 'Create comment with API'
        run: |
          gh api -X POST \
            http://api.github.com/repo/${ORGANIZATION}/${REPOSITORY}/issues/ISSUE_NUMBER/comments \
            -f body='
            comment from the api call made by milito himself
            '

         env:
            GITHUB_TOKEN: ${{secrets.GITHUB_SECRET}}
            ORGANIZATION: ${{github.events.organization.login}}
            REPOSITORY: ${{github.events.repository.name}}
            ISSUE_NUMBER: ${{github.event.issue.number}}
